setw -g mode-keys vi
# 'v' で選択を始める
bind -T copy-mode-vi v send -X begin-selection
# 選択範囲をコピーしてもコピーモードを終わらせない
bind -T copy-mode-vi M-w send -X copy-selection

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# ペイン開始番号
set-option -g base-index 1

# -r の連続入力待機ミリ秒。デフォは500
set-option -g repeat-time 10000

### エスケープシーケンスの待ち時間をなくす
# https://github.com/microsoft/WSL/issues/5931
set-option -s escape-time 10

### バックスクロール行数(デフォルト2000)
set-option -g history-limit 10000

# prefixキーをC-qに変更
set -g prefix C-g
bind-key C-g send-prefix
unbind C-b

# status line の背景色を指定する。
set-option -g status-bg colour24

# マウス対応
set-option -g mouse on

# status line の文字色を指定する。
set-option -g status-fg colour255

### Prefix + Ctrl-Rで設定ファイルリロード
bind C-r source-file ~/.tmux.conf \; display "Reloaded!"


# ペインを分割する
bind -n C-M-j split-window -v
bind -n C-M-l split-window -h
unbind %

# vimのキーバインドでペインを移動する
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# vimのキーバインドでペインをリサイズする
bind -r S-h resize-pane -L
bind -r S-j resize-pane -D
bind -r S-k resize-pane -U
bind -r S-l resize-pane -R

## ペインのインデックスを1から始める
setw -g pane-base-index 1
